:toc: left
= jQAssistant Docker Plugin

== Overview

The jQAssistant Docker plugin provides a scanner for Docker registries gathering information about:

- Repositories
- Tags
- Manifests and their configurations
- Layers (Blobs)

The scanner uses the Docker Registry HTTP API V2 as described https://docs.docker.com/registry/spec/api/[here].

Incremental scans are supported, i.e. new or updated tags will be detected.

NOTE: There is no official release available yet.
For testing the plugin clone this repository and build it locally using ```mvn clean install```.

== Scan Docker Registry

=== Maven

The plugin can be enabled in a Maven based project by adding it as a dependency to the jQAssistant Maven plugin:

[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>com.buschmais.jqassistant</groupId>
            <artifactId>jqassistant-maven-plugin</artifactId>
            <version>1.8.0</version>
            <executions>
                <execution>
                    <id>default-cli</id>
                    <goals>
                        <goal>scan</goal>
                    </goals>
                    <configuration>
                        <scanProperties>
                            <docker.repositories.include>*</docker.repositories.include>
                            <!--
                            <docker.repositories.exclude></docker.repositories.exclude>
                            -->
                        </scanProperties>
                        <scanIncludes>
                            <scanInclude>
                                <url>http://my-docker-registry:5000</url>
                                <scope>docker:registry</scope>
                            </scanInclude>
                        </scanIncludes>
                    </configuration>
                </execution>
            </executions>
            <!-- The jqassistant-docker-plugin goes here -->
            <dependencies>
                <dependency>
                    <groupId>org.jqassistant.contrib.plugin</groupId>
                    <artifactId>jqassistant-docker-plugin</artifactId>
                    <version>1.8.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
----

Afterwards a scan can be triggered and the server started:

----
mvn jqassistant:scan
mvn jqassistant:server
----

=== Command Line Distribution

Download the shaded JAR file from https://search.maven.org/artifact/org.jqassistant.contrib.plugin/jqassistant-docker-plugin[Maven Central] and put it into the `/plugins` folder of the distribution.

----
bin/jqassistant.sh scan -u docker:registry::http://my-docker-registry:5000
bin/jqassistant.sh server
----

=== Self-Signed Certificates

If the Docker registry uses HTTPS with a self-signed certificate the latter must be imported into the keystore of the Java Runtime Environment:

----
$JAVA_HOME/bin/keytool -import -alias JIRA -file jira.crt -keystore $JAVA_HOME/lib/security/cacerts
----

TIP: The certificate can be exported directly from a web browser (e.g. as DER encoded-binary X509), the default passwort of the JRE keystore is `changeit`.

== Example Queries

[source,cypher]
.All registry urls and contained repositories.
----
MATCH
  (registry:Docker:Registry)-[:CONTAINS_REPOSITORY]->(repository:Docker:Repository)
RETURN
  registry.url, collect(repository.name) AS repositories
----

[source,cypher]
.All tags for repository ```centos```.
----
MATCH
  (repository:Docker:Repository{name:'centos'})-[:CONTAINS_TAG]->(tag:Docker:Tag)
RETURN
  tag.name
----

[source,cypher]
.Manifest, config, labels and image for repository ```centos``` with the tag ```latest```.
----
MATCH
  (repository:Docker:Repository{name:'centos'})-[:CONTAINS_TAG]->(tag:Docker:Tag{name:'latest'}),
  (tag)-[:HAS_MANIFEST]->(manifest:Docker:Manifest)-[:HAS_CONFIG]->(config:Docker:Config)
OPTIONAL MATCH
  (config)-[:HAS_LABEL]->(label:Docker:Label)
OPTIONAL MATCH
  (config)-[:FOR_IMAGE]->(image:Docker:Image)
RETURN
  manifest, config, label, image
----

[source,cypher]
.Layers for repository ```centos``` with tag ```latest```.
----
MATCH
  (repository:Docker:Repository{name:'centos'})-[:CONTAINS_TAG]->(tag:Docker:Tag{name:'latest'}),
  (tag)-[:HAS_MANIFEST]->(manifest:Docker:Manifest),
  (manifest:Docker:Manifest)-[declaresLayer:DECLARES_LAYER]->(layer:Docker:Blob)
RETURN
  declaresLayer.index, layer.digest, layer.size
ORDER BY
  declaresLayer.index
----

[source,cypher]
.Aggregated blob size per repository
----
MATCH
  (repository:Docker:Repository)-[:CONTAINS_TAG]->(tag:Docker:Tag),
  (tag)-[:HAS_MANIFEST]->(:Docker:Manifest)-[:DECLARES_LAYER]->(layer:Docker:Blob)
RETURN
  repository.name as repository, sum(layer.size)/(1024*1024) as repositorySizeMB
ORDER BY
  repositorySizeMB desc
----

== Known Limitations

* Authentication is not (yet) supported
